const path = require('path');
const { makeProduct, cartFromProducts } = require(path.join(__dirname, '../../core/runtime/fixtures'));

const IMAGE = {
  emptyPlaceholder: 'https://demo.salla.sa/assets/images/placeholder.png',
};

const T = {
  laptop1:     'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=700',
  laptop2:     'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=700',
  laptop3:     'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&q=80&w=700',
  phone1:      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&q=80&w=700',
  phone2:      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=700',
  tablet:      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=700',
  headphones:  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=700',
  airpods:     'https://images.unsplash.com/photo-1588423771073-b8903fead714?auto=format&fit=crop&q=80&w=700',
  camera1:     'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=700',
  camera2:     'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&q=80&w=700',
  watch:       'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=700',
  monitor:     'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=700',
  keyboard:    'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=700',
  mouse:       'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=700',
  speaker:     'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=700',
  gaming:      'https://images.unsplash.com/photo-1593640408182-31c228a84278?auto=format&fit=crop&q=80&w=700',
  router:      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=700',
  tv:          'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&q=80&w=700',
  drone:       'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&q=80&w=700',
  ssd:         'https://images.unsplash.com/photo-1597138804456-e7dca7f59d54?auto=format&fit=crop&q=80&w=700',
  chair:       'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&q=80&w=700',
  software:    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=700',
  techHero:    'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1600',
  techBanner:  'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&q=80&w=1400',
  techSquare:  'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=900',
  gamingBanner:'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=1400',
  offerBanner: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=1400',
};

const techProducts = [
  makeProduct({ id: 301, name: 'MacBook Pro 16" معالج M3 Pro', subtitle: 'أداء استثنائي لمحترفي الإبداع والبرمجة', price: 9499, sale_price: 9499, regular_price: 10999, product_price: 10999, is_on_sale: true, status: 'sale', type: 'product', quantity: 14, sold_quantity: 1284, promotion_title: 'وفّر 1500 ر.س', sku: 'APPL-MBP16-M3PRO-512', has_metadata: true, metadata: [{ name: 'المعالج', value: 'Apple M3 Pro — 12 نواة' }, { name: 'الذاكرة العشوائية', value: '18 جيجابايت موحدة' }, { name: 'التخزين', value: 'SSD 512 جيجابايت' }, { name: 'الشاشة', value: '16.2" Liquid Retina XDR — 3456×2234' }, { name: 'البطارية', value: 'تدوم حتى 22 ساعة' }, { name: 'نظام التشغيل', value: 'macOS Sonoma' }, { name: 'الوزن', value: '2.14 كجم' }, { name: 'المنافذ', value: 'Thunderbolt 4 ×3، HDMI، SD Card، MagSafe 3' }], images: [{ id: '301-1', url: T.laptop1, alt: 'MacBook Pro 16"', type: 'image' }, { id: '301-2', url: T.laptop2, alt: 'MacBook Pro 16" مفتوح', type: 'image' }, { id: '301-3', url: T.laptop3, alt: 'MacBook Pro 16" جانبي', type: 'image' }], tags: ['apple', 'laptop', 'sale'], categories: [{ id: 301, name: 'أجهزة المحمول', url: 'categories/laptops.html' }], image: { url: T.laptop1, alt: 'MacBook Pro 16"' }, thumbnail: T.laptop1, rating: { stars: 5, count: 892 }, weight: '2.14 كجم', weight_label: '2.14 كجم', can_show_sold: true }),
  makeProduct({ id: 302, name: 'Dell XPS 15 — Core i9 — RTX 4070', subtitle: 'لاب توب احترافي للمطورين والمصممين', price: 7299, sale_price: 7299, regular_price: 7299, product_price: 7299, is_on_sale: false, status: 'sale', type: 'product', quantity: 8, sold_quantity: 456, sku: 'DELL-XPS15-I9-4070', has_metadata: true, metadata: [{ name: 'المعالج', value: 'Intel Core i9-13900H — 14 نواة' }, { name: 'الذاكرة العشوائية', value: '32 جيجابايت DDR5' }, { name: 'التخزين', value: 'SSD NVMe 1 تيرابايت' }, { name: 'الشاشة', value: '15.6" OLED 3.5K 60Hz' }, { name: 'كرت الشاشة', value: 'NVIDIA RTX 4070 8GB' }, { name: 'البطارية', value: '86 وات/ساعة' }, { name: 'نظام التشغيل', value: 'Windows 11 Pro' }, { name: 'الوزن', value: '1.86 كجم' }], images: [{ id: '302-1', url: T.laptop2, alt: 'Dell XPS 15', type: 'image' }, { id: '302-2', url: T.laptop3, alt: 'Dell XPS 15 مفتوح', type: 'image' }], tags: ['dell', 'laptop', 'gaming'], categories: [{ id: 301, name: 'أجهزة المحمول', url: 'categories/laptops.html' }], image: { url: T.laptop2, alt: 'Dell XPS 15' }, thumbnail: T.laptop2, rating: { stars: 4, count: 341 } }),
  makeProduct({ id: 303, name: 'ASUS ROG Strix G16 — AMD Ryzen 9 — RX 7700S', subtitle: 'لاب توب ألعاب بشاشة 240Hz — نفدت الكمية', price: 5499, sale_price: 4799, regular_price: 5499, product_price: 5499, is_on_sale: true, status: 'out', type: 'product', quantity: 0, sold_quantity: 2103, promotion_title: 'خصم نهاية الموسم', sku: 'ASUS-ROG-G16-RX7700', has_metadata: true, metadata: [{ name: 'المعالج', value: 'AMD Ryzen 9 7945HX — 16 نواة' }, { name: 'الذاكرة العشوائية', value: '16 جيجابايت DDR5' }, { name: 'التخزين', value: 'SSD NVMe 512 جيجابايت' }, { name: 'الشاشة', value: '16" FHD 240Hz' }, { name: 'كرت الشاشة', value: 'AMD RX 7700S 8GB' }, { name: 'الوزن', value: '2.3 كجم' }], notify_availability: { enabled: true, label: 'أبلغني عند التوفر' }, images: [{ id: '303-1', url: T.gaming, alt: 'ASUS ROG Strix G16', type: 'image' }, { id: '303-2', url: T.laptop3, alt: 'ASUS ROG لوحة المفاتيح', type: 'image' }], tags: ['asus', 'gaming', 'sale'], categories: [{ id: 301, name: 'أجهزة المحمول', url: 'categories/laptops.html' }, { id: 307, name: 'الألعاب', url: 'categories/gaming.html' }], image: { url: T.gaming, alt: 'ASUS ROG Strix G16' }, thumbnail: T.gaming, rating: { stars: 5, count: 1547 } }),
  makeProduct({ id: 304, name: 'iPhone 15 Pro Max — 256GB — تيتانيوم أسود', subtitle: 'كاميرا 48MP وشريحة A17 Pro وشاشة Super Retina XDR', price: 5299, sale_price: 4999, regular_price: 5299, product_price: 5299, is_on_sale: true, status: 'sale', type: 'product', quantity: 31, sold_quantity: 3812, promotion_title: 'خصم 300 ر.س', sku: 'APPL-IP15PM-256-BLK', has_metadata: true, metadata: [{ name: 'الشاشة', value: '6.7" Super Retina XDR — 2796×1290' }, { name: 'المعالج', value: 'Apple A17 Pro — 6 نوى' }, { name: 'التخزين', value: '256 جيجابايت' }, { name: 'الكاميرا', value: 'رئيسية 48MP + واسعة 12MP + تيليفوتو 12MP' }, { name: 'البطارية', value: '4422 مللي أمبير' }, { name: 'مقاومة الماء', value: 'IP68 — عمق 6 أمتار' }, { name: 'الاتصال', value: '5G، Wi-Fi 6E، Bluetooth 5.3' }, { name: 'الوزن', value: '221 جرام' }], options: [{ name: 'اللون', type: 'color', values: [{ name: 'تيتانيوم أسود', color: '#4A4A4A', price: 0 }, { name: 'تيتانيوم أبيض', color: '#E8E4DC', price: 0 }, { name: 'تيتانيوم طبيعي', color: '#C8B89A', price: 0 }] }], images: [{ id: '304-1', url: T.phone1, alt: 'iPhone 15 Pro Max', type: 'image' }, { id: '304-2', url: T.phone2, alt: 'iPhone 15 Pro Max خلفي', type: 'image' }], tags: ['apple', 'iphone', 'sale', 'new'], categories: [{ id: 302, name: 'الجوالات', url: 'categories/phones.html' }], image: { url: T.phone1, alt: 'iPhone 15 Pro Max' }, thumbnail: T.phone1, rating: { stars: 5, count: 2341 } }),
  makeProduct({ id: 305, name: 'Samsung Galaxy S24 Ultra — 512GB — تيتانيوم رمادي', subtitle: 'قلم S Pen مدمج وكاميرا 200MP ومعالج Snapdragon 8 Gen 3', price: 5799, sale_price: 5799, regular_price: 5799, product_price: 5799, is_on_sale: false, status: 'sale', type: 'product', quantity: 22, sold_quantity: 1908, sku: 'SAMS-S24U-512-TIT', has_metadata: true, metadata: [{ name: 'الشاشة', value: '6.8" Dynamic AMOLED 2X — 120Hz' }, { name: 'المعالج', value: 'Snapdragon 8 Gen 3' }, { name: 'الذاكرة', value: '12 جيجابايت RAM' }, { name: 'التخزين', value: '512 جيجابايت' }, { name: 'الكاميرا', value: 'رباعية — رئيسية 200MP' }, { name: 'البطارية', value: '5000 مللي أمبير — شحن 45W' }, { name: 'قلم S Pen', value: 'مدمج — كمون 2.8 ملي ثانية' }, { name: 'مقاومة الماء', value: 'IP68' }], images: [{ id: '305-1', url: T.phone2, alt: 'Samsung Galaxy S24 Ultra', type: 'image' }, { id: '305-2', url: T.phone1, alt: 'Samsung S24 Ultra أمامي', type: 'image' }], tags: ['samsung', 'android', 'new'], categories: [{ id: 302, name: 'الجوالات', url: 'categories/phones.html' }], image: { url: T.phone2, alt: 'Samsung Galaxy S24 Ultra' }, thumbnail: T.phone2, rating: { stars: 5, count: 1102 } }),
  makeProduct({ id: 306, name: 'iPad Pro 12.9" — M2 — Wi-Fi — 256GB', subtitle: 'شاشة Liquid Retina XDR مع ProMotion 120Hz', price: 4299, sale_price: 3999, regular_price: 4299, product_price: 4299, is_on_sale: true, status: 'sale', type: 'product', quantity: 18, sold_quantity: 742, promotion_title: 'خصم 300 ر.س', sku: 'APPL-IPADPRO129-M2-256', has_metadata: true, metadata: [{ name: 'الشاشة', value: '12.9" Liquid Retina XDR — ProMotion 120Hz' }, { name: 'المعالج', value: 'Apple M2 — 8 نوى' }, { name: 'التخزين', value: '256 جيجابايت' }, { name: 'الكاميرا الخلفية', value: 'واسعة 12MP + LiDAR' }, { name: 'القلم المتوافق', value: 'Apple Pencil الجيل الثاني' }, { name: 'البطارية', value: 'تدوم حتى 10 ساعات' }], tags: ['apple', 'tablet', 'sale'], categories: [{ id: 302, name: 'الجوالات والتابلت', url: 'categories/phones.html' }], image: { url: T.tablet, alt: 'iPad Pro 12.9"' }, thumbnail: T.tablet, rating: { stars: 5, count: 538 } }),
  makeProduct({ id: 307, name: 'Sony WH-1000XM5 — سماعات لاسلكية', subtitle: 'إلغاء ضوضاء استثنائي مع صوت Hi-Res وبطارية 30 ساعة', price: 1299, sale_price: 1099, regular_price: 1299, product_price: 1299, is_on_sale: true, status: 'sale', type: 'product', quantity: 45, sold_quantity: 4201, promotion_title: 'خصم 200 ر.س', sku: 'SONY-WH1000XM5-BLK', has_metadata: true, metadata: [{ name: 'إلغاء الضوضاء', value: 'Dual Noise Sensor — 8 ميكروفون' }, { name: 'الاتصال', value: 'Bluetooth 5.2 — متعدد النقاط' }, { name: 'عمر البطارية', value: '30 ساعة' }, { name: 'الشحن السريع', value: '3 ساعات من شحن 3 دقائق' }, { name: 'الترميز', value: 'LDAC، AAC، SBC' }, { name: 'الوزن', value: '250 جرام' }], images: [{ id: '307-1', url: T.headphones, alt: 'Sony WH-1000XM5', type: 'image' }], tags: ['sony', 'headphones', 'sale', 'bestseller'], categories: [{ id: 303, name: 'الصوت والسماعات', url: 'categories/audio.html' }], image: { url: T.headphones, alt: 'Sony WH-1000XM5' }, thumbnail: T.headphones, rating: { stars: 5, count: 3187 } }),
  makeProduct({ id: 308, name: 'Apple AirPods Pro الجيل الثاني', subtitle: 'صوت أكمل وإلغاء ضوضاء أقوى مع شاحن MagSafe', price: 999, sale_price: 999, regular_price: 999, product_price: 999, is_on_sale: false, status: 'out', type: 'product', quantity: 0, sold_quantity: 5834, sku: 'APPL-AIRPODSPRO2', notify_availability: { enabled: true, label: 'أبلغني عند التوفر' }, images: [{ id: '308-1', url: T.airpods, alt: 'AirPods Pro الجيل الثاني', type: 'image' }], tags: ['apple', 'airpods'], categories: [{ id: 303, name: 'الصوت والسماعات', url: 'categories/audio.html' }], image: { url: T.airpods, alt: 'AirPods Pro الجيل الثاني' }, thumbnail: T.airpods, rating: { stars: 5, count: 4212 } }),
  makeProduct({ id: 309, name: 'Sony Alpha A7 IV — كاميرا بدون مرآة Full-Frame', subtitle: 'مستشعر 33MP ومتابعة الهدف بالذكاء الاصطناعي', price: 11299, sale_price: 11299, regular_price: 11299, product_price: 11299, is_on_sale: false, status: 'sale', type: 'product', quantity: 6, sold_quantity: 318, sku: 'SONY-A7IV-BODY', has_metadata: true, metadata: [{ name: 'المستشعر', value: 'Full-Frame BSI CMOS — 33 ميجابكسل' }, { name: 'معالج الصورة', value: 'BIONZ XR' }, { name: 'تثبيت الصورة', value: 'In-Body 5.5 stop' }, { name: 'الفيديو', value: '4K 60fps 10-bit 4:2:2' }, { name: 'التركيز', value: 'Real-time Tracking + Eye AF' }, { name: 'الوزن', value: '658 جرام' }], images: [{ id: '309-1', url: T.camera1, alt: 'Sony Alpha A7 IV', type: 'image' }, { id: '309-2', url: T.camera2, alt: 'Sony A7 IV جانبي', type: 'image' }], tags: ['sony', 'camera', 'professional'], categories: [{ id: 304, name: 'الكاميرات والتصوير', url: 'categories/cameras.html' }], image: { url: T.camera1, alt: 'Sony Alpha A7 IV' }, thumbnail: T.camera1, rating: { stars: 5, count: 214 } }),
  makeProduct({ id: 310, name: 'GoPro Hero 12 Black', subtitle: 'تصوير 5.3K بثبات HyperSmooth 6.0 ومقاومة الماء', price: 1799, sale_price: 1499, regular_price: 1799, product_price: 1799, is_on_sale: true, status: 'sale', type: 'product', quantity: 27, sold_quantity: 987, promotion_title: 'خصم 300 ر.س', sku: 'GOPRO-HERO12-BLK', images: [{ id: '310-1', url: T.camera2, alt: 'GoPro Hero 12 Black', type: 'image' }], tags: ['gopro', 'camera', 'sale', 'outdoor'], categories: [{ id: 304, name: 'الكاميرات والتصوير', url: 'categories/cameras.html' }], image: { url: T.camera2, alt: 'GoPro Hero 12 Black' }, thumbnail: T.camera2, rating: { stars: 4, count: 732 } }),
  makeProduct({ id: 311, name: 'Apple Watch Ultra 2 — 49mm — تيتانيوم', subtitle: 'للرياضيين والمغامرين — GPS دقيق وبطارية 60 ساعة', price: 3699, sale_price: 3699, regular_price: 3699, product_price: 3699, is_on_sale: false, status: 'sale', type: 'product', quantity: 11, sold_quantity: 621, sku: 'APPL-WATCHULTRA2-49TIT', has_metadata: true, metadata: [{ name: 'الشاشة', value: '49mm LTPO OLED — 2000 نيت' }, { name: 'GPS', value: 'GPS، GLONASS، Galileo، L5' }, { name: 'مقاومة الماء', value: '100 متر + غطس' }, { name: 'البطارية', value: 'تدوم حتى 60 ساعة' }, { name: 'الاتصال', value: 'LTE، Wi-Fi 6، Bluetooth 5.3' }], tags: ['apple', 'watch', 'sport'], categories: [{ id: 305, name: 'الساعات الذكية', url: 'categories/smartwatches.html' }], image: { url: T.watch, alt: 'Apple Watch Ultra 2' }, thumbnail: T.watch, rating: { stars: 5, count: 448 } }),
  makeProduct({ id: 312, name: 'Samsung Odyssey G7 32" — 4K 144Hz', subtitle: 'شاشة QLED مقوسة 1000R بتغطية 95% DCI-P3', price: 3499, sale_price: 2999, regular_price: 3499, product_price: 3499, is_on_sale: true, status: 'sale', type: 'product', quantity: 9, sold_quantity: 512, promotion_title: 'خصم 500 ر.س', sku: 'SAMS-G7-32-4K144', has_metadata: true, metadata: [{ name: 'الحجم', value: '32 بوصة' }, { name: 'نوع اللوحة', value: 'VA QLED مقوسة 1000R' }, { name: 'الدقة', value: '4K UHD 3840×2160' }, { name: 'معدل التحديث', value: '144Hz — G-Sync + FreeSync Premium Pro' }, { name: 'زمن الاستجابة', value: '1ms (MPRT)' }, { name: 'السطوع', value: '600 نيت HDR1000' }, { name: 'المنافذ', value: 'HDMI 2.1 ×2، DisplayPort 1.4، USB-A ×2' }], tags: ['samsung', 'monitor', 'gaming', 'sale'], categories: [{ id: 306, name: 'الشاشات والملحقات', url: 'categories/monitors.html' }], image: { url: T.monitor, alt: 'Samsung Odyssey G7 32"' }, thumbnail: T.monitor, rating: { stars: 4, count: 389 } }),
  makeProduct({ id: 313, name: 'Keychron Q3 Pro — لوحة مفاتيح ميكانيكية لاسلكية', subtitle: 'هيكل ألومنيوم CNC ومفاتيح Gateron Red وحشو صوتي', price: 699, sale_price: 699, regular_price: 699, product_price: 699, is_on_sale: false, status: 'sale', type: 'product', quantity: 34, sold_quantity: 1843, sku: 'KEYCH-Q3PRO-RED', tags: ['keyboard', 'mechanical', 'wireless', 'bestseller'], categories: [{ id: 306, name: 'الشاشات والملحقات', url: 'categories/monitors.html' }], image: { url: T.keyboard, alt: 'Keychron Q3 Pro' }, thumbnail: T.keyboard, rating: { stars: 5, count: 1204 } }),
  makeProduct({ id: 314, name: 'Logitech MX Master 3S — ماوس لاسلكي', subtitle: 'عجلة مغناطيسية صامتة ودقة 8000 DPI واتصال ثلاثي', price: 449, sale_price: 379, regular_price: 449, product_price: 449, is_on_sale: true, status: 'sale', type: 'product', quantity: 67, sold_quantity: 3421, promotion_title: 'خصم 70 ر.س', sku: 'LOGI-MXMASTER3S-GRY', tags: ['logitech', 'mouse', 'sale', 'bestseller'], categories: [{ id: 306, name: 'الشاشات والملحقات', url: 'categories/monitors.html' }], image: { url: T.mouse, alt: 'Logitech MX Master 3S' }, thumbnail: T.mouse, rating: { stars: 5, count: 2876 } }),
  makeProduct({ id: 315, name: 'Sonos Era 300 — مكبر صوت ذكي Dolby Atmos', subtitle: 'صوت Spatial Audio وتكامل Alexa وApple AirPlay 2', price: 2199, sale_price: 2199, regular_price: 2199, product_price: 2199, is_on_sale: false, status: 'sale', type: 'product', quantity: 15, sold_quantity: 267, sku: 'SONOS-ERA300-WHT', tags: ['sonos', 'speaker', 'smart-home'], categories: [{ id: 308, name: 'المنزل الذكي', url: 'categories/smarthome.html' }], image: { url: T.speaker, alt: 'Sonos Era 300' }, thumbnail: T.speaker, rating: { stars: 5, count: 183 } }),
  makeProduct({ id: 316, name: 'باقة محطة العمل الاحترافية — شاشة + لوحة مفاتيح + ماوس', subtitle: 'توفير 750 ر.س — مجهزة للمصممين والمطورين', price: 4999, sale_price: 4249, regular_price: 4999, product_price: 4999, is_on_sale: true, status: 'sale', type: 'bundle', quantity: 5, sold_quantity: 89, promotion_title: 'وفّر 750 ر.س', sku: 'BNDL-WORKSTATION-PRO', tags: ['bundle', 'workstation', 'sale'], categories: [{ id: 306, name: 'الشاشات والملحقات', url: 'categories/monitors.html' }], image: { url: T.monitor, alt: 'باقة محطة العمل الاحترافية' }, thumbnail: T.monitor, rating: { stars: 5, count: 74 } }),
  makeProduct({ id: 317, name: 'TP-Link Archer BE800 — راوتر Wi-Fi 7 ثلاثي النطاق', subtitle: 'سرعة 19 جيجابت/ثانية ومنافذ 10G LAN', price: 1899, sale_price: 1899, regular_price: 1899, product_price: 1899, is_on_sale: false, status: 'sale', type: 'product', quantity: 23, sold_quantity: 731, sku: 'TPLINK-BE800-WHT', has_metadata: true, metadata: [{ name: 'المعيار', value: 'Wi-Fi 7 — ثلاثي النطاق' }, { name: 'السرعة القصوى', value: '19 جيجابت/ثانية' }, { name: 'المنافذ', value: '10G WAN، 10G LAN ×2، 2.5G LAN ×4' }, { name: 'الهوائيات', value: '8 هوائيات خارجية' }], tags: ['tp-link', 'router', 'wifi7'], categories: [{ id: 308, name: 'المنزل الذكي', url: 'categories/smarthome.html' }], image: { url: T.router, alt: 'TP-Link Archer BE800' }, thumbnail: T.router, rating: { stars: 4, count: 512 } }),
  makeProduct({ id: 318, name: 'Samsung Neo QLED 65" 8K — QN900C', subtitle: 'تلفزيون 8K بمعالج Neural Quantum — نفدت الكمية', price: 18999, sale_price: 18999, regular_price: 22999, product_price: 22999, is_on_sale: true, status: 'out', type: 'product', quantity: 0, sold_quantity: 142, promotion_title: 'عرض خاص — نفدت', sku: 'SAMS-QN900C-65-8K', has_metadata: true, metadata: [{ name: 'الحجم', value: '65 بوصة' }, { name: 'الدقة', value: '8K 7680×4320' }, { name: 'اللوحة', value: 'Neo QLED MiniLED' }, { name: 'معدل التحديث', value: '120Hz' }, { name: 'الصوت', value: 'Dolby Atmos — 80W' }], notify_availability: { enabled: true, label: 'أبلغني عند التوفر' }, tags: ['samsung', 'tv', 'sale'], categories: [{ id: 308, name: 'المنزل الذكي', url: 'categories/smarthome.html' }], image: { url: T.tv, alt: 'Samsung Neo QLED 65"' }, thumbnail: T.tv, rating: { stars: 5, count: 98 } }),
  makeProduct({ id: 319, name: 'DJI Mavic 3 Pro — طائرة مسيّرة 4/3 CMOS', subtitle: 'ثلاث كاميرات Hasselblad وتحليق 43 دقيقة — طلب مسبق', price: 9999, sale_price: 9999, regular_price: 9999, product_price: 9999, is_on_sale: false, status: 'sale', type: 'product', quantity: 0, sold_quantity: 0, has_preorder_campaign: true, preorder: { label: 'احجز الآن — يصل في 3 أسابيع' }, sku: 'DJI-MAVIC3PRO-FLY', has_metadata: true, metadata: [{ name: 'الكاميرا الرئيسية', value: '4/3 CMOS Hasselblad — 20MP' }, { name: 'الفيديو', value: '4K/60fps، 5.1K/50fps DCI' }, { name: 'وقت الطيران', value: '43 دقيقة' }, { name: 'المدى', value: '15 كم (O3+)' }, { name: 'مقاومة الرياح', value: 'مستوى 7' }], tags: ['dji', 'drone', 'preorder'], categories: [{ id: 304, name: 'الكاميرات والتصوير', url: 'categories/cameras.html' }], image: { url: T.drone, alt: 'DJI Mavic 3 Pro' }, thumbnail: T.drone, rating: { stars: 5, count: 0 } }),
  makeProduct({ id: 320, name: 'Windows 11 Pro — ترخيص رقمي أصلي', subtitle: 'تسليم فوري عبر البريد — دعم مدى الحياة', price: 499, sale_price: 399, regular_price: 499, product_price: 499, is_on_sale: true, status: 'sale', type: 'digital', quantity: 9999, sold_quantity: 12483, promotion_title: 'خصم 100 ر.س', sku: 'MS-WIN11PRO-ESD', digital_files_settings: { delivery_type: 'email', show_download_button: false }, tags: ['microsoft', 'software', 'digital', 'sale', 'bestseller'], categories: [{ id: 301, name: 'أجهزة المحمول', url: 'categories/laptops.html' }], image: { url: T.software, alt: 'Windows 11 Pro' }, thumbnail: T.software, rating: { stars: 4, count: 5621 } }),
  makeProduct({ id: 321, name: 'Samsung T7 Shield — SSD محمول 2TB', subtitle: 'سرعة 1050 MB/s ومقاوم للصدمات والماء IP65', price: 549, sale_price: 449, regular_price: 549, product_price: 549, is_on_sale: true, status: 'sale', type: 'product', quantity: 88, sold_quantity: 6742, promotion_title: 'خصم 100 ر.س', sku: 'SAMS-T7SHIELD-2TB-BLU', tags: ['samsung', 'storage', 'sale', 'bestseller'], categories: [{ id: 306, name: 'الشاشات والملحقات', url: 'categories/monitors.html' }], image: { url: T.ssd, alt: 'Samsung T7 Shield 2TB' }, thumbnail: T.ssd, rating: { stars: 5, count: 4891 } }),
  makeProduct({ id: 322, name: 'كرسي ألعاب Secretlab TITAN Evo 2022', subtitle: 'جلد SoftWeave ودعم قطني قابل للضبط', price: 2199, sale_price: 1799, regular_price: 2199, product_price: 2199, is_on_sale: true, status: 'sale', type: 'product', quantity: 4, sold_quantity: 834, promotion_title: 'خصم 400 ر.س', sku: 'SECRETLAB-TITAN-EVO22-M', options: [{ name: 'الحجم', type: 'size', values: [{ name: 'Small — 150-170 سم', price: 0 }, { name: 'Medium — 170-185 سم', price: 0 }, { name: 'XL — +185 سم', price: 150 }] }], tags: ['gaming', 'chair', 'sale'], categories: [{ id: 307, name: 'الألعاب', url: 'categories/gaming.html' }], image: { url: T.chair, alt: 'Secretlab TITAN Evo 2022' }, thumbnail: T.chair, rating: { stars: 5, count: 612 } }),
];

const techReviews = [
  { id: 51, product_id: 301, name: 'محمد الدوسري', user: 'محمد الدوسري', avatar: 'https://i.pravatar.cc/150?u=mdosari', stars: 5, rating: 5, text: 'اشتريت MacBook Pro لأول مرة بعد سنوات مع ويندوز — المعالج M3 Pro يتعامل مع ملفات After Effects بدون أدنى تأخير. التوصيل في 24 ساعة.', content: 'اشتريت MacBook Pro لأول مرة — المعالج M3 Pro خرافي للمونتاج.', created_at: '2026-04-28' },
  { id: 52, product_id: 304, name: 'سارة الغامدي', user: 'سارة الغامدي', avatar: 'https://i.pravatar.cc/150?u=sghamdi', stars: 5, rating: 5, text: 'iPhone 15 Pro Max يستحق كل ريال. كاميرا التيليفوتو تلتقط تفاصيل لم أكن أتخيلها. التوصيل في اليوم التالي!', content: 'iPhone 15 Pro Max يستحق كل ريال — كاميرا لا تصدق.', created_at: '2026-04-25' },
  { id: 53, product_id: 307, name: 'خالد الرشيد', user: 'خالد الرشيد', avatar: 'https://i.pravatar.cc/150?u=krashid', stars: 5, rating: 5, text: 'Sony XM5 مع طيران ساعتين — لم أسمع أي ضوضاء من المحركات. أفضل استثمار للمسافرين.', content: 'Sony XM5 — أفضل إلغاء ضوضاء في السوق.', created_at: '2026-04-20' },
  { id: 54, product_id: 302, name: 'نورة العتيبي', user: 'نورة العتيبي', avatar: 'https://i.pravatar.cc/150?u=notibi', stars: 4, rating: 4, text: 'Dell XPS 15 ممتاز للمصممين — شاشة OLED خرافية. البطارية تستنزف أسرع عند تشغيل RTX 4070 بكامل طاقتها.', content: 'Dell XPS 15 — شاشة OLED خرافية لكن الشاحن ثقيل.', created_at: '2026-04-17' },
  { id: 55, product_id: 321, name: 'عبدالله حسن', user: 'عبدالله حسن', avatar: 'https://i.pravatar.cc/150?u=ahasan', stars: 5, rating: 5, text: 'Samsung T7 Shield هو الثالث الذي أشتريه من تيك زون. الأول لا يزال يعمل منذ 4 سنوات. جودة موثوقة.', content: 'اشتريت 3 نسخ — الأول لا يزال يعمل منذ 4 سنوات.', created_at: '2026-04-14' },
  { id: 56, product_id: 305, name: 'ريم الشمري', user: 'ريم الشمري', avatar: 'https://i.pravatar.cc/150?u=rshamri', stars: 5, rating: 5, text: 'Galaxy S24 Ultra بعد أسبوعين — قلم S Pen غيّر طريقة عملي كلياً. التقطت صوراً احترافية في حفل زفاف بدون كاميرا!', content: 'Galaxy S24 Ultra — قلم S Pen يغير طريقة العمل.', created_at: '2026-04-10' },
  { id: 57, product_id: 312, name: 'فيصل المطيري', user: 'فيصل المطيري', avatar: 'https://i.pravatar.cc/150?u=fmutairi', stars: 4, rating: 4, text: 'شاشة Odyssey G7 رائعة للألعاب والتصميم. لكن التعريف يحتاج ضبطاً أولياً للحصول على ألوان دقيقة.', content: 'شاشة رائعة لكن تحتاج معايرة أولية للألوان.', created_at: '2026-04-05' },
  { id: 58, product_id: 320, name: 'ماجد البقمي', user: 'ماجد البقمي', avatar: 'https://i.pravatar.cc/150?u=mbaqmi', stars: 5, rating: 5, text: 'وصل الترخيص خلال 10 دقائق من الشراء. تفعّل بنقرة واحدة.', content: 'وصل الترخيص في 10 دقائق — تجربة شراء مثالية.', created_at: '2026-03-30' },
  { id: 59, product_id: 309, name: 'أحمد القرني', user: 'أحمد القرني', avatar: 'https://i.pravatar.cc/150?u=aqarni', stars: 5, rating: 5, text: 'Sony A7 IV كاميرا استثنائية لمصور الأفراح. Eye AF تتبع العيون في الإضاءة الخافتة.', content: 'Sony A7 IV — Eye AF لا يقبل المنافسة.', created_at: '2026-03-22' },
  { id: 60, product_id: 313, name: 'لمى العمري', user: 'لمى العمري', avatar: 'https://i.pravatar.cc/150?u=lomari', stars: 4, rating: 4, text: 'Keychron Q3 Pro صوت المفاتيح مريح للمكتب. البناء الألومنيوم فاخر. الاتصال اللاسلكي مستقر تماماً.', content: 'Keychron Q3 Pro — بناء فاخر وصوت هادئ مريح.', created_at: '2026-03-15' },
  { id: 61, product_id: 303, name: 'سلطان الحارثي', user: 'سلطان الحارثي', avatar: 'https://i.pravatar.cc/150?u=sharbi', stars: 2, rating: 2, text: 'الجهاز رائع لكن وجدت بعد شرائه أن سعره انخفض 300 ريال في متجر آخر. كنت أتمنى تنبيهاً مسبقاً.', content: 'الأداء ممتاز لكن السعر لم يكن الأفضل في ذلك اليوم.', created_at: '2026-03-08' },
  { id: 62, product_id: 314, name: 'هند السبيعي', user: 'هند السبيعي', avatar: 'https://i.pravatar.cc/150?u=hsubaie', stars: 5, rating: 5, text: 'Logitech MX Master 3S — اشتريت النسخة الأولى قبل 3 سنوات من تيك زون وما زالت تعمل. الآن مع الثالثة.', content: 'اشتريت 3 نسخ على مر السنين — ولاء كامل للمتجر.', created_at: '2026-03-01' },
];

const techStore = {
  id: 2,
  name: 'تيك زون — TechZone',
  username: 'techzone',
  description: 'وجهتك الموثوقة للتقنية منذ 2017 — أجهزة أصلية، ضمان رسمي، توصيل سريع.',
  slogan: 'تقنية أصيلة، ثقة دائمة',
  logo: IMAGE.emptyPlaceholder,
  url: 'index.html',
  api: '#',
  icon: '',
  contacts: { mobile: '+966500001111', phone: '+96612000111', email: 'support@techzone.test', whatsapp: '+966500001111' },
  social: { instagram: 'techzone_sa', twitter: 'techzone_sa', snapchat: 'techzone_sa', youtube: 'techzone_sa' },
  settings: {
    is_multilingual: true,
    currencies_enabled: true,
    arabic_numbers_enabled: true,
    rating_enabled: true,
    auth: { email_allowed: true, mobile_allowed: true, is_email_required: false },
    cart: { apply_coupon_enabled: true },
    product: { total_sold_enabled: true, fit_type: 'contain', show_price_as_dash: false },
    category: { testimonial_enabled: true },
    blog: { allow_likes_and_comments: true },
    rating: { enabled: true, show_on_product: true, allow_update: true, update_period: 14 },
    tax: { number: '310567891200003', certificate: IMAGE.emptyPlaceholder, taxable_prices_enabled: true },
  },
};

module.exports = {
  'tech-store': {
    id: 'tech-store',
    title: 'Tech Store — متجر تقني ناضج',
    purpose: 'متجر تقني غني يحاكي متجراً يعمل منذ سنوات — منتجات بجداول مواصفات، خصومات، نفاد كمية، طلب مسبق، رقمي، حزمة.',
    store: techStore,
    user: {
      id: 601, type: 'user', name: 'أحمد الزهراني', email: 'ahmed@example.test', mobile: '+966500002222',
      avatar: 'https://i.pravatar.cc/150?u=azahrani', can_access_wallet: true, wallet: { balance: 340 },
      wishlist: [301, 304, 307, 311, 319], loyalty_points: 4820,
    },
    users: [
      { id: null, type: 'guest', name: 'زائر', can_access_wallet: false, wishlist: [] },
      { id: 601, type: 'user', name: 'أحمد الزهراني', email: 'ahmed@example.test', mobile: '+966500002222', avatar: 'https://i.pravatar.cc/150?u=azahrani', can_access_wallet: true, wallet: { balance: 340 }, wishlist: [301, 304, 307, 311, 319], loyalty_points: 4820 },
      { id: 602, type: 'user', name: 'عميل VIP — عبدالرحمن السلمي', email: 'vip@example.test', mobile: '+966500003333', avatar: 'https://i.pravatar.cc/150?u=arsalmi', can_access_wallet: true, wallet: { balance: 1850 }, wishlist: [301, 302, 304, 305, 307, 309, 311, 312, 318], loyalty_points: 18400 },
    ],
    products: techProducts,
    cart: cartFromProducts(techProducts.slice(0, 4), { coupon: { code: 'TECH10', discount: 500 }, total_discount: 500 }),
    reviews: techReviews,
    testimonials: techReviews.filter((r) => r.stars >= 4).map((r) => ({ name: r.name, text: r.content, avatar: r.avatar || IMAGE.emptyPlaceholder, stars: r.stars })),
    categories: [
      { id: 301, name: 'أجهزة المحمول واللابتوب', url: 'categories/laptops.html', icon: 'sicon-laptop', image: T.laptop1 },
      { id: 302, name: 'الجوالات والتابلت', url: 'categories/phones.html', icon: 'sicon-mobile', image: T.phone1 },
      { id: 303, name: 'الصوت والسماعات', url: 'categories/audio.html', icon: 'sicon-headphone', image: T.headphones },
      { id: 304, name: 'الكاميرات والتصوير', url: 'categories/cameras.html', icon: 'sicon-camera', image: T.camera1 },
      { id: 305, name: 'الساعات الذكية', url: 'categories/smartwatches.html', icon: 'sicon-watch', image: T.watch },
      { id: 306, name: 'الشاشات والملحقات', url: 'categories/monitors.html', icon: 'sicon-screen', image: T.monitor },
      { id: 307, name: 'الألعاب والترفيه', url: 'categories/gaming.html', icon: 'sicon-game', image: T.gaming },
      { id: 308, name: 'المنزل الذكي والشبكات', url: 'categories/smarthome.html', icon: 'sicon-home', image: T.router },
    ],
    brands: [
      { id: 11, name: 'Apple', url: 'brands/apple.html', logo: IMAGE.emptyPlaceholder },
      { id: 12, name: 'Samsung', url: 'brands/samsung.html', logo: IMAGE.emptyPlaceholder },
      { id: 13, name: 'Sony', url: 'brands/sony.html', logo: IMAGE.emptyPlaceholder },
      { id: 14, name: 'Dell', url: 'brands/dell.html', logo: IMAGE.emptyPlaceholder },
      { id: 15, name: 'Logitech', url: 'brands/logitech.html', logo: IMAGE.emptyPlaceholder },
      { id: 16, name: 'DJI', url: 'brands/dji.html', logo: IMAGE.emptyPlaceholder },
      { id: 17, name: 'ASUS', url: 'brands/asus.html', logo: IMAGE.emptyPlaceholder },
      { id: 18, name: 'TP-Link', url: 'brands/tplink.html', logo: IMAGE.emptyPlaceholder },
    ],
    orders: [
      { id: 9101, status: 'delivered', total: 10498, created_at: '2026-04-10', items: techProducts.filter((p) => [301, 314].includes(p.id)) },
      { id: 9102, status: 'processing', total: 4999, created_at: '2026-04-28', items: techProducts.filter((p) => p.id === 304) },
      { id: 9103, status: 'delivered', total: 1099, created_at: '2026-03-15', items: techProducts.filter((p) => p.id === 307) },
      { id: 9104, status: 'pending', total: 399, created_at: '2026-05-01', items: techProducts.filter((p) => p.id === 320) },
      { id: 9105, status: 'delivered', total: 449, created_at: '2026-02-20', items: techProducts.filter((p) => p.id === 321) },
    ],
    blog: [
      { id: 11, title: 'MacBook Pro M3 مقابل Windows — أيهما يناسبك في 2026؟', url: 'blog/macbook-vs-windows.html', image: T.laptop1, likes_count: 142, comments_count: 38, created_at: '2026-04-20', tags: [{ name: 'مقارنات', url: '#' }] },
      { id: 12, title: 'أفضل 5 سماعات لاسلكية في السوق السعودي', url: 'blog/best-headphones-2026.html', image: T.headphones, likes_count: 89, comments_count: 21, created_at: '2026-04-12', tags: [{ name: 'صوت', url: '#' }] },
      { id: 13, title: 'كيف تختار شاشة الألعاب المثالية — دليل شامل', url: 'blog/gaming-monitor-guide.html', image: T.monitor, likes_count: 201, comments_count: 54, created_at: '2026-03-28', tags: [{ name: 'ألعاب', url: '#' }] },
      { id: 14, title: 'Samsung Galaxy S24 Ultra — مراجعة شاملة بعد شهر استخدام', url: 'blog/s24-ultra-review.html', image: T.phone2, likes_count: 317, comments_count: 76, created_at: '2026-03-15', tags: [{ name: 'مراجعات', url: '#' }] },
      { id: 15, title: 'Wi-Fi 7 — هل يستحق الترقية الآن؟', url: 'blog/wifi7-guide.html', image: T.router, likes_count: 67, comments_count: 15, created_at: '2026-03-02', tags: [{ name: 'شبكات', url: '#' }] },
      { id: 16, title: 'أفضل إعداد مكتبي للمطورين والمصممين في 2026', url: 'blog/best-desk-setup.html', image: T.techSquare, likes_count: 455, comments_count: 112, created_at: '2026-02-18', tags: [{ name: 'إعداد مكتبي', url: '#' }] },
    ],
    home: {
      slides: [
        { image: T.techHero, title: 'تقنية أصيلة — ضمان رسمي', description: 'أكثر من 9 سنوات من الثقة والجودة في السوق السعودي.', without_overlay: false },
        { image: T.offerBanner, title: 'عروض الربيع — خصومات تصل إلى 30%', description: 'احصل على أحدث الأجهزة بأسعار لا تتكرر. العرض لفترة محدودة.', without_overlay: false },
        { image: T.gamingBanner, title: 'موسم الألعاب — أجهزة، شاشات، كراسي', description: 'مجهّز محطة العمل الاحترافية بأفضل مكونات سوق الألعاب.', without_overlay: false },
      ],
      banners: [
        { image: T.techBanner, url: 'categories/laptops.html', title: 'أجهزة المحمول', description: 'MacBook وDell وASUS — أصلية بضمان' },
        { image: T.gamingBanner, url: 'categories/gaming.html', title: 'عالم الألعاب', description: 'شاشات وكراسي وملحقات احترافية' },
        { image: T.techSquare, url: 'categories/phones.html', title: 'الجوالات الذكية', description: 'iPhone وSamsung — أحدث الإصدارات' },
      ],
      links: [
        { icon: 'sicon-laptop', title: 'اللابتوب', url: 'categories/laptops.html' },
        { icon: 'sicon-mobile', title: 'الجوالات', url: 'categories/phones.html' },
        { icon: 'sicon-headphone', title: 'السماعات', url: 'categories/audio.html' },
        { icon: 'sicon-camera', title: 'الكاميرات', url: 'categories/cameras.html' },
        { icon: 'sicon-game', title: 'الألعاب', url: 'categories/gaming.html' },
        { icon: 'sicon-offer', title: 'العروض', url: 'product.html' },
      ],
      features: [
        { icon: 'sicon-shipping-fast', title: 'توصيل في 24 ساعة', text: 'لجميع مناطق المملكة' },
        { icon: 'sicon-shield-check', title: 'منتجات أصلية 100%', text: 'ضمان رسمي من الوكيل' },
        { icon: 'sicon-return-box', title: 'إرجاع مجاني 14 يوماً', text: 'سياسة إرجاع واضحة وسريعة' },
        { icon: 'sicon-headset', title: 'دعم فني متخصص', text: 'فريق تقني 7 أيام في الأسبوع' },
      ],
    },
    expectations: {
      minProducts: 20,
      minReviews: 10,
      requiredProductTypes: ['product', 'digital', 'bundle'],
      requiresSaleProduct: true,
      requiresOutOfStockProduct: true,
      requiresPreorderProduct: true,
      requiresRegisteredUser: true,
    },
  },
};
